#!/bin/sh

start() {
    usr/local/m5stack/lt8618sxb_mcu_config &> /dev/null &
	/sbin/agetty  --noclear tty1 linux 2>&1 > /dev/null &
}
stop() {
	killall -9 agetty
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
