#!/bin/sh
#
# Start/stop exampled
#

DAEMON=/usr/bin/exampled
PIDFILE=/var/run/exampled/pid

case "$1" in
  start)
	echo "Starting exampled..."
	start-stop-daemon -S -b -x "$DAEMON" -p "$PIDFILE"
	;;
  stop)
	echo "Stopping exampled..."
	start-stop-daemon -K -x "$DAEMON" -p "$PIDFILE" -o
	;;
  restart)
	"$0" stop
	sleep 1 # Prevent race condition: ensure stops before start.
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
